// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.dsproject.authenticationservices;

public final class AuthenticationServicesImpl {
  private AuthenticationServicesImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticationservices_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authenticationservices_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticationservices_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authenticationservices_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticationservices_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authenticationservices_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticationservices_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authenticationservices_LogoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\026authenticationservices\"" +
      "2\n\014LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\">\n\rLoginResponse\022\027\n\017response" +
      "Message\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"\'\n\rL" +
      "ogoutRequest\022\026\n\016requestMessage\030\001 \001(\005\")\n\016" +
      "LogoutResponse\022\027\n\017responseMessage\030\001 \001(\t2" +
      "\313\001\n\026AuthenticationServices\022V\n\005login\022$.au" +
      "thenticationservices.LoginRequest\032%.auth" +
      "enticationservices.LoginResponse\"\000\022Y\n\006lo" +
      "gout\022%.authenticationservices.LogoutRequ" +
      "est\032&.authenticationservices.LogoutRespo" +
      "nse\"\000BD\n$com.dsproject.authenticationser" +
      "vicesB\032AuthenticationServicesImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authenticationservices_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authenticationservices_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authenticationservices_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_authenticationservices_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authenticationservices_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authenticationservices_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_authenticationservices_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_authenticationservices_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authenticationservices_LogoutRequest_descriptor,
        new java.lang.String[] { "RequestMessage", });
    internal_static_authenticationservices_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_authenticationservices_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authenticationservices_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
