// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.dsproject.accountservices;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:accountservices.Empty)
    com.google.protobuf.MessageOrBuilder {
}
