// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.dsproject.authenticationservices;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authenticationservices.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
