// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.dsproject.authenticationservices;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authenticationservices.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestMessage = 1;</code>
   */
  int getRequestMessage();
}
