// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.dsproject.accountservices;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:accountservices.LogoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
