// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombookingservice.proto

package com.dsproject.roombookingservice;

public interface BookRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:roombookingservice.BookRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string roomName = 2;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>string numAttendees = 3;</code>
   */
  java.lang.String getNumAttendees();
  /**
   * <code>string numAttendees = 3;</code>
   */
  com.google.protobuf.ByteString
      getNumAttendeesBytes();

  /**
   * <code>string foodRequired = 4;</code>
   */
  java.lang.String getFoodRequired();
  /**
   * <code>string foodRequired = 4;</code>
   */
  com.google.protobuf.ByteString
      getFoodRequiredBytes();

  /**
   * <code>string drinksRequired = 5;</code>
   */
  java.lang.String getDrinksRequired();
  /**
   * <code>string drinksRequired = 5;</code>
   */
  com.google.protobuf.ByteString
      getDrinksRequiredBytes();
}
