// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombookingservice.proto

package com.dsproject.roombookingservice;

public interface BookRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:roombookingservice.BookRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string time = 2;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>int32 numAttendees = 3;</code>
   */
  int getNumAttendees();

  /**
   * <code>string foodRequired = 4;</code>
   */
  java.lang.String getFoodRequired();
  /**
   * <code>string foodRequired = 4;</code>
   */
  com.google.protobuf.ByteString
      getFoodRequiredBytes();

  /**
   * <code>string drinksRequired = 5;</code>
   */
  java.lang.String getDrinksRequired();
  /**
   * <code>string drinksRequired = 5;</code>
   */
  com.google.protobuf.ByteString
      getDrinksRequiredBytes();
}
