// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombookingservice.proto

package com.dsproject.roombookingservice;

public interface BookRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:roombookingservice.BookRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookingConfirmation = 1;</code>
   */
  java.lang.String getBookingConfirmation();
  /**
   * <code>string bookingConfirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getBookingConfirmationBytes();

  /**
   * <code>string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>int32 numAttendees = 4;</code>
   */
  int getNumAttendees();

  /**
   * <code>string cateringRequirements = 5;</code>
   */
  java.lang.String getCateringRequirements();
  /**
   * <code>string cateringRequirements = 5;</code>
   */
  com.google.protobuf.ByteString
      getCateringRequirementsBytes();

  /**
   * <code>string roomName = 6;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 6;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();
}
