// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombookingservice.proto

package com.dsproject.roombookingservice;

public interface CheckAvailableRoomsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:roombookingservice.CheckAvailableRoomsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string roomName = 2;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>string availableTimes = 3;</code>
   */
  java.lang.String getAvailableTimes();
  /**
   * <code>string availableTimes = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvailableTimesBytes();
}
