// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombookingservice.proto

package com.dsproject.roombookingservice;

public final class RoomBookingServiceImpl {
  private RoomBookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roombookingservice_CheckAvailableRoomsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roombookingservice_CheckAvailableRoomsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roombookingservice_CheckAvailableRoomsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roombookingservice_CheckAvailableRoomsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roombookingservice_BookRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roombookingservice_BookRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roombookingservice_BookRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roombookingservice_BookRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030roombookingservice.proto\022\022roombookings" +
      "ervice\"<\n\032CheckAvailableRoomsRequest\022\014\n\004" +
      "date\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\"U\n\033CheckAva" +
      "ilableRoomsResponse\022\014\n\004date\030\001 \001(\t\022\020\n\010roo" +
      "mName\030\002 \001(\t\022\026\n\016availableTimes\030\003 \001(\t\"q\n\017B" +
      "ookRoomRequest\022\014\n\004date\030\001 \001(\t\022\014\n\004time\030\002 \001" +
      "(\t\022\024\n\014numAttendees\030\003 \001(\005\022\024\n\014foodRequired" +
      "\030\004 \001(\t\022\026\n\016drinksRequired\030\005 \001(\t\"v\n\020BookRo" +
      "omResponse\022\014\n\004date\030\001 \001(\t\022\020\n\010roomName\030\002 \001" +
      "(\t\022\024\n\014numAttendees\030\003 \001(\t\022\024\n\014foodRequired" +
      "\030\004 \001(\t\022\026\n\016drinksRequired\030\005 \001(\t2\351\001\n\022RoomB" +
      "ookingService\022z\n\023checkAvailableRooms\022..r" +
      "oombookingservice.CheckAvailableRoomsReq" +
      "uest\032/.roombookingservice.CheckAvailable" +
      "RoomsResponse\"\0000\001\022W\n\010bookRoom\022#.roombook" +
      "ingservice.BookRoomRequest\032$.roombooking" +
      "service.BookRoomResponse\"\000B<\n com.dsproj" +
      "ect.roombookingserviceB\026RoomBookingServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_roombookingservice_CheckAvailableRoomsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_roombookingservice_CheckAvailableRoomsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roombookingservice_CheckAvailableRoomsRequest_descriptor,
        new java.lang.String[] { "Date", "Location", });
    internal_static_roombookingservice_CheckAvailableRoomsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_roombookingservice_CheckAvailableRoomsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roombookingservice_CheckAvailableRoomsResponse_descriptor,
        new java.lang.String[] { "Date", "RoomName", "AvailableTimes", });
    internal_static_roombookingservice_BookRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_roombookingservice_BookRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roombookingservice_BookRoomRequest_descriptor,
        new java.lang.String[] { "Date", "Time", "NumAttendees", "FoodRequired", "DrinksRequired", });
    internal_static_roombookingservice_BookRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_roombookingservice_BookRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roombookingservice_BookRoomResponse_descriptor,
        new java.lang.String[] { "Date", "RoomName", "NumAttendees", "FoodRequired", "DrinksRequired", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
