// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public interface AddExpenseClaimResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeexpenseservice.AddExpenseClaimResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string claimResult = 1;</code>
   */
  java.lang.String getClaimResult();
  /**
   * <code>string claimResult = 1;</code>
   */
  com.google.protobuf.ByteString
      getClaimResultBytes();
}
