// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

/**
 * Protobuf type {@code employeeexpenseservice.AddMultiExpenseClaimRequest}
 */
public  final class AddMultiExpenseClaimRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employeeexpenseservice.AddMultiExpenseClaimRequest)
    AddMultiExpenseClaimRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddMultiExpenseClaimRequest.newBuilder() to construct.
  private AddMultiExpenseClaimRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddMultiExpenseClaimRequest() {
    department_ = "";
    expenseType_ = "";
    amount_ = 0D;
    expenseClaimNo_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddMultiExpenseClaimRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            department_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            expenseType_ = s;
            break;
          }
          case 25: {

            amount_ = input.readDouble();
            break;
          }
          case 32: {

            expenseClaimNo_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.class, com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.Builder.class);
  }

  public static final int DEPARTMENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object department_;
  /**
   * <code>string department = 1;</code>
   */
  public java.lang.String getDepartment() {
    java.lang.Object ref = department_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      department_ = s;
      return s;
    }
  }
  /**
   * <code>string department = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDepartmentBytes() {
    java.lang.Object ref = department_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      department_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPENSETYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object expenseType_;
  /**
   * <code>string expenseType = 2;</code>
   */
  public java.lang.String getExpenseType() {
    java.lang.Object ref = expenseType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expenseType_ = s;
      return s;
    }
  }
  /**
   * <code>string expenseType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getExpenseTypeBytes() {
    java.lang.Object ref = expenseType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      expenseType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private double amount_;
  /**
   * <code>double amount = 3;</code>
   */
  public double getAmount() {
    return amount_;
  }

  public static final int EXPENSECLAIMNO_FIELD_NUMBER = 4;
  private int expenseClaimNo_;
  /**
   * <code>int32 expenseClaimNo = 4;</code>
   */
  public int getExpenseClaimNo() {
    return expenseClaimNo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDepartmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, department_);
    }
    if (!getExpenseTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, expenseType_);
    }
    if (amount_ != 0D) {
      output.writeDouble(3, amount_);
    }
    if (expenseClaimNo_ != 0) {
      output.writeInt32(4, expenseClaimNo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDepartmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, department_);
    }
    if (!getExpenseTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, expenseType_);
    }
    if (amount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, amount_);
    }
    if (expenseClaimNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, expenseClaimNo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest)) {
      return super.equals(obj);
    }
    com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest other = (com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest) obj;

    boolean result = true;
    result = result && getDepartment()
        .equals(other.getDepartment());
    result = result && getExpenseType()
        .equals(other.getExpenseType());
    result = result && (
        java.lang.Double.doubleToLongBits(getAmount())
        == java.lang.Double.doubleToLongBits(
            other.getAmount()));
    result = result && (getExpenseClaimNo()
        == other.getExpenseClaimNo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
    hash = (53 * hash) + getDepartment().hashCode();
    hash = (37 * hash) + EXPENSETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getExpenseType().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + EXPENSECLAIMNO_FIELD_NUMBER;
    hash = (53 * hash) + getExpenseClaimNo();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employeeexpenseservice.AddMultiExpenseClaimRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employeeexpenseservice.AddMultiExpenseClaimRequest)
      com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.class, com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.Builder.class);
    }

    // Construct using com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      department_ = "";

      expenseType_ = "";

      amount_ = 0D;

      expenseClaimNo_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_descriptor;
    }

    @java.lang.Override
    public com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest getDefaultInstanceForType() {
      return com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest build() {
      com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest buildPartial() {
      com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest result = new com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest(this);
      result.department_ = department_;
      result.expenseType_ = expenseType_;
      result.amount_ = amount_;
      result.expenseClaimNo_ = expenseClaimNo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest) {
        return mergeFrom((com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest other) {
      if (other == com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest.getDefaultInstance()) return this;
      if (!other.getDepartment().isEmpty()) {
        department_ = other.department_;
        onChanged();
      }
      if (!other.getExpenseType().isEmpty()) {
        expenseType_ = other.expenseType_;
        onChanged();
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (other.getExpenseClaimNo() != 0) {
        setExpenseClaimNo(other.getExpenseClaimNo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object department_ = "";
    /**
     * <code>string department = 1;</code>
     */
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        department_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string department = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string department = 1;</code>
     */
    public Builder setDepartment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      department_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string department = 1;</code>
     */
    public Builder clearDepartment() {
      
      department_ = getDefaultInstance().getDepartment();
      onChanged();
      return this;
    }
    /**
     * <code>string department = 1;</code>
     */
    public Builder setDepartmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      department_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object expenseType_ = "";
    /**
     * <code>string expenseType = 2;</code>
     */
    public java.lang.String getExpenseType() {
      java.lang.Object ref = expenseType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expenseType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string expenseType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExpenseTypeBytes() {
      java.lang.Object ref = expenseType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expenseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expenseType = 2;</code>
     */
    public Builder setExpenseType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expenseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string expenseType = 2;</code>
     */
    public Builder clearExpenseType() {
      
      expenseType_ = getDefaultInstance().getExpenseType();
      onChanged();
      return this;
    }
    /**
     * <code>string expenseType = 2;</code>
     */
    public Builder setExpenseTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      expenseType_ = value;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 3;</code>
     */
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 3;</code>
     */
    public Builder setAmount(double value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 3;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0D;
      onChanged();
      return this;
    }

    private int expenseClaimNo_ ;
    /**
     * <code>int32 expenseClaimNo = 4;</code>
     */
    public int getExpenseClaimNo() {
      return expenseClaimNo_;
    }
    /**
     * <code>int32 expenseClaimNo = 4;</code>
     */
    public Builder setExpenseClaimNo(int value) {
      
      expenseClaimNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 expenseClaimNo = 4;</code>
     */
    public Builder clearExpenseClaimNo() {
      
      expenseClaimNo_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employeeexpenseservice.AddMultiExpenseClaimRequest)
  }

  // @@protoc_insertion_point(class_scope:employeeexpenseservice.AddMultiExpenseClaimRequest)
  private static final com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest();
  }

  public static com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddMultiExpenseClaimRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddMultiExpenseClaimRequest>() {
    @java.lang.Override
    public AddMultiExpenseClaimRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddMultiExpenseClaimRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddMultiExpenseClaimRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddMultiExpenseClaimRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dsproject.employeeexpenseservice.AddMultiExpenseClaimRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

