// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public interface AddMultiExpenseClaimRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeexpenseservice.AddMultiExpenseClaimRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string department = 1;</code>
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 1;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>string expenseType = 2;</code>
   */
  java.lang.String getExpenseType();
  /**
   * <code>string expenseType = 2;</code>
   */
  com.google.protobuf.ByteString
      getExpenseTypeBytes();

  /**
   * <code>double amount = 3;</code>
   */
  double getAmount();

  /**
   * <code>int32 expenseClaimNo = 4;</code>
   */
  int getExpenseClaimNo();
}
