// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public interface CheckExpenseClaimResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeexpenseservice.CheckExpenseClaimResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string claimNumber = 1;</code>
   */
  java.lang.String getClaimNumber();
  /**
   * <code>string claimNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getClaimNumberBytes();

  /**
   * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
   */
  com.dsproject.employeeexpenseservice.ClaimStatus getStatus();

  /**
   * <code>double amount = 3;</code>
   */
  double getAmount();
}
