// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public interface CheckExpenseClaimRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeexpenseservice.CheckExpenseClaimRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 checkAllExpenses = 1;</code>
   */
  int getCheckAllExpenses();
}
