// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

/**
 * Protobuf type {@code employeeexpenseservice.CheckExpenseClaimResponse}
 */
public  final class CheckExpenseClaimResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employeeexpenseservice.CheckExpenseClaimResponse)
    CheckExpenseClaimResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckExpenseClaimResponse.newBuilder() to construct.
  private CheckExpenseClaimResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckExpenseClaimResponse() {
    claimNumber_ = "";
    status_ = 0;
    amount_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckExpenseClaimResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            claimNumber_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 25: {

            amount_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_CheckExpenseClaimResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_CheckExpenseClaimResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.class, com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.Builder.class);
  }

  public static final int CLAIMNUMBER_FIELD_NUMBER = 1;
  private volatile java.lang.Object claimNumber_;
  /**
   * <code>string claimNumber = 1;</code>
   */
  public java.lang.String getClaimNumber() {
    java.lang.Object ref = claimNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      claimNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string claimNumber = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClaimNumberBytes() {
    java.lang.Object ref = claimNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      claimNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
   */
  public com.dsproject.employeeexpenseservice.ClaimStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.dsproject.employeeexpenseservice.ClaimStatus result = com.dsproject.employeeexpenseservice.ClaimStatus.valueOf(status_);
    return result == null ? com.dsproject.employeeexpenseservice.ClaimStatus.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private double amount_;
  /**
   * <code>double amount = 3;</code>
   */
  public double getAmount() {
    return amount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClaimNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, claimNumber_);
    }
    if (status_ != com.dsproject.employeeexpenseservice.ClaimStatus.SENT_FOR_APPROVAL.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (amount_ != 0D) {
      output.writeDouble(3, amount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClaimNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, claimNumber_);
    }
    if (status_ != com.dsproject.employeeexpenseservice.ClaimStatus.SENT_FOR_APPROVAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (amount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, amount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse)) {
      return super.equals(obj);
    }
    com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse other = (com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse) obj;

    boolean result = true;
    result = result && getClaimNumber()
        .equals(other.getClaimNumber());
    result = result && status_ == other.status_;
    result = result && (
        java.lang.Double.doubleToLongBits(getAmount())
        == java.lang.Double.doubleToLongBits(
            other.getAmount()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLAIMNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getClaimNumber().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employeeexpenseservice.CheckExpenseClaimResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employeeexpenseservice.CheckExpenseClaimResponse)
      com.dsproject.employeeexpenseservice.CheckExpenseClaimResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_CheckExpenseClaimResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_CheckExpenseClaimResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.class, com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.Builder.class);
    }

    // Construct using com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      claimNumber_ = "";

      status_ = 0;

      amount_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.internal_static_employeeexpenseservice_CheckExpenseClaimResponse_descriptor;
    }

    @java.lang.Override
    public com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse getDefaultInstanceForType() {
      return com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse build() {
      com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse buildPartial() {
      com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse result = new com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse(this);
      result.claimNumber_ = claimNumber_;
      result.status_ = status_;
      result.amount_ = amount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse) {
        return mergeFrom((com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse other) {
      if (other == com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse.getDefaultInstance()) return this;
      if (!other.getClaimNumber().isEmpty()) {
        claimNumber_ = other.claimNumber_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object claimNumber_ = "";
    /**
     * <code>string claimNumber = 1;</code>
     */
    public java.lang.String getClaimNumber() {
      java.lang.Object ref = claimNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        claimNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string claimNumber = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClaimNumberBytes() {
      java.lang.Object ref = claimNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        claimNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string claimNumber = 1;</code>
     */
    public Builder setClaimNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      claimNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string claimNumber = 1;</code>
     */
    public Builder clearClaimNumber() {
      
      claimNumber_ = getDefaultInstance().getClaimNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string claimNumber = 1;</code>
     */
    public Builder setClaimNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      claimNumber_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
     */
    public com.dsproject.employeeexpenseservice.ClaimStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.dsproject.employeeexpenseservice.ClaimStatus result = com.dsproject.employeeexpenseservice.ClaimStatus.valueOf(status_);
      return result == null ? com.dsproject.employeeexpenseservice.ClaimStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
     */
    public Builder setStatus(com.dsproject.employeeexpenseservice.ClaimStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.employeeexpenseservice.ClaimStatus status = 2;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 3;</code>
     */
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 3;</code>
     */
    public Builder setAmount(double value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 3;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employeeexpenseservice.CheckExpenseClaimResponse)
  }

  // @@protoc_insertion_point(class_scope:employeeexpenseservice.CheckExpenseClaimResponse)
  private static final com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse();
  }

  public static com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckExpenseClaimResponse>
      PARSER = new com.google.protobuf.AbstractParser<CheckExpenseClaimResponse>() {
    @java.lang.Override
    public CheckExpenseClaimResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckExpenseClaimResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckExpenseClaimResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckExpenseClaimResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dsproject.employeeexpenseservice.CheckExpenseClaimResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

