// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

/**
 * Protobuf enum {@code employeeexpenseservice.ClaimStatus}
 */
public enum ClaimStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SENT_FOR_APPROVAL = 0;</code>
   */
  SENT_FOR_APPROVAL(0),
  /**
   * <code>APPROVED = 1;</code>
   */
  APPROVED(1),
  /**
   * <code>DENIED = 2;</code>
   */
  DENIED(2),
  /**
   * <code>PAID = 3;</code>
   */
  PAID(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SENT_FOR_APPROVAL = 0;</code>
   */
  public static final int SENT_FOR_APPROVAL_VALUE = 0;
  /**
   * <code>APPROVED = 1;</code>
   */
  public static final int APPROVED_VALUE = 1;
  /**
   * <code>DENIED = 2;</code>
   */
  public static final int DENIED_VALUE = 2;
  /**
   * <code>PAID = 3;</code>
   */
  public static final int PAID_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClaimStatus valueOf(int value) {
    return forNumber(value);
  }

  public static ClaimStatus forNumber(int value) {
    switch (value) {
      case 0: return SENT_FOR_APPROVAL;
      case 1: return APPROVED;
      case 2: return DENIED;
      case 3: return PAID;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClaimStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClaimStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClaimStatus>() {
          public ClaimStatus findValueByNumber(int number) {
            return ClaimStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dsproject.employeeexpenseservice.EmployeeExpenseServiceImpl.getDescriptor().getEnumTypes().get(1);
  }

  private static final ClaimStatus[] VALUES = values();

  public static ClaimStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ClaimStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:employeeexpenseservice.ClaimStatus)
}

