// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public final class EmployeeExpenseServiceImpl {
  private EmployeeExpenseServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_AddExpenseClaimRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_AddExpenseClaimRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_AddExpenseClaimResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_AddExpenseClaimResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_AddMultiExpenseClaimResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_AddMultiExpenseClaimResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_UploadExpenseReceiptsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_UploadExpenseReceiptsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_UploadExpenseReceiptsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_UploadExpenseReceiptsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_CheckExpenseClaimRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_CheckExpenseClaimRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employeeexpenseservice_CheckExpenseClaimResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employeeexpenseservice_CheckExpenseClaimResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036employee_expense_service.proto\022\026employ" +
      "eeexpenseservice\"k\n\026AddExpenseClaimReque" +
      "st\022\022\n\ndepartment\030\001 \001(\t\022\023\n\013expenseType\030\002 " +
      "\001(\t\022\020\n\010totalAmt\030\003 \001(\001\022\026\n\016expenseClaimNo\030" +
      "\004 \001(\005\".\n\027AddExpenseClaimResponse\022\023\n\013clai" +
      "mResult\030\001 \001(\t\"n\n\033AddMultiExpenseClaimReq" +
      "uest\022\022\n\ndepartment\030\001 \001(\t\022\023\n\013expenseType\030" +
      "\002 \001(\t\022\016\n\006amount\030\003 \001(\001\022\026\n\016expenseClaimNo\030" +
      "\004 \001(\005\"I\n\034AddMultiExpenseClaimResponse\022\024\n" +
      "\014runningTotal\030\002 \001(\001\022\023\n\013claimResult\030\001 \001(\t" +
      "\"d\n\034UploadExpenseReceiptsRequest\022\014\n\004data" +
      "\030\001 \001(\014\022\014\n\004size\030\002 \001(\003\022\020\n\010fileName\030\003 \001(\t\022\026" +
      "\n\016actualFileSize\030\004 \001(\003\"o\n\035UploadExpenseR" +
      "eceiptsResponse\022\020\n\010fileName\030\001 \001(\t\022\014\n\004siz" +
      "e\030\002 \001(\003\022.\n\006status\030\003 \001(\0162\036.employeeexpens" +
      "eservice.Status\"4\n\030CheckExpenseClaimRequ" +
      "est\022\030\n\020checkAllExpenses\030\001 \001(\005\"u\n\031CheckEx" +
      "penseClaimResponse\022\023\n\013claimNumber\030\001 \001(\t\022" +
      "3\n\006status\030\002 \001(\0162#.employeeexpenseservice" +
      ".ClaimStatus\022\016\n\006amount\030\003 \001(\001*@\n\006Status\022\013" +
      "\n\007PENDING\020\000\022\017\n\013IN_PROGRESS\020\001\022\014\n\010UPLOADED" +
      "\020\002\022\n\n\006FAILED\020\003*H\n\013ClaimStatus\022\025\n\021SENT_FO" +
      "R_APPROVAL\020\000\022\014\n\010APPROVED\020\001\022\n\n\006DENIED\020\002\022\010" +
      "\n\004PAID\020\0032\241\004\n\026EmployeeExpenseService\022t\n\017a" +
      "ddExpenseClaim\022..employeeexpenseservice." +
      "AddExpenseClaimRequest\032/.employeeexpense" +
      "service.AddExpenseClaimResponse\"\000\022\207\001\n\024ad" +
      "dMultiExpenseClaim\0223.employeeexpenseserv" +
      "ice.AddMultiExpenseClaimRequest\0324.employ" +
      "eeexpenseservice.AddMultiExpenseClaimRes" +
      "ponse\"\000(\0010\001\022\210\001\n\025uploadExpenseReceipts\0224." +
      "employeeexpenseservice.UploadExpenseRece" +
      "iptsRequest\0325.employeeexpenseservice.Upl" +
      "oadExpenseReceiptsResponse\"\000(\001\022|\n\021checkE" +
      "xpenseClaim\0220.employeeexpenseservice.Che" +
      "ckExpenseClaimRequest\0321.employeeexpenses" +
      "ervice.CheckExpenseClaimResponse\"\0000\001BD\n$" +
      "com.dsproject.employeeexpenseserviceB\032Em" +
      "ployeeExpenseServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_employeeexpenseservice_AddExpenseClaimRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employeeexpenseservice_AddExpenseClaimRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_AddExpenseClaimRequest_descriptor,
        new java.lang.String[] { "Department", "ExpenseType", "TotalAmt", "ExpenseClaimNo", });
    internal_static_employeeexpenseservice_AddExpenseClaimResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_employeeexpenseservice_AddExpenseClaimResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_AddExpenseClaimResponse_descriptor,
        new java.lang.String[] { "ClaimResult", });
    internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_AddMultiExpenseClaimRequest_descriptor,
        new java.lang.String[] { "Department", "ExpenseType", "Amount", "ExpenseClaimNo", });
    internal_static_employeeexpenseservice_AddMultiExpenseClaimResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_employeeexpenseservice_AddMultiExpenseClaimResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_AddMultiExpenseClaimResponse_descriptor,
        new java.lang.String[] { "RunningTotal", "ClaimResult", });
    internal_static_employeeexpenseservice_UploadExpenseReceiptsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_employeeexpenseservice_UploadExpenseReceiptsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_UploadExpenseReceiptsRequest_descriptor,
        new java.lang.String[] { "Data", "Size", "FileName", "ActualFileSize", });
    internal_static_employeeexpenseservice_UploadExpenseReceiptsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_employeeexpenseservice_UploadExpenseReceiptsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_UploadExpenseReceiptsResponse_descriptor,
        new java.lang.String[] { "FileName", "Size", "Status", });
    internal_static_employeeexpenseservice_CheckExpenseClaimRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_employeeexpenseservice_CheckExpenseClaimRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_CheckExpenseClaimRequest_descriptor,
        new java.lang.String[] { "CheckAllExpenses", });
    internal_static_employeeexpenseservice_CheckExpenseClaimResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_employeeexpenseservice_CheckExpenseClaimResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employeeexpenseservice_CheckExpenseClaimResponse_descriptor,
        new java.lang.String[] { "ClaimNumber", "Status", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
