// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public interface UploadExpenseReceiptsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeexpenseservice.UploadExpenseReceiptsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int64 size = 2;</code>
   */
  long getSize();

  /**
   * <code>.employeeexpenseservice.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.employeeexpenseservice.Status status = 3;</code>
   */
  com.dsproject.employeeexpenseservice.Status getStatus();
}
