// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_expense_service.proto

package com.dsproject.employeeexpenseservice;

public interface UploadExpenseReceiptsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeexpenseservice.UploadExpenseReceiptsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int64 size = 2;</code>
   */
  long getSize();

  /**
   * <code>string fileName = 3;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int64 actualFileSize = 4;</code>
   */
  long getActualFileSize();
}
